[package]
name = "pglite-sys"
version = "0.0.0"
edition = "2021"

[build-dependencies]
bindgen = "0.61"
cc = { version = "1.0", features = ["parallel"] }
pglite-buildtools = { path = "../pglite-buildtools" }
